{-# LANGUAGE CPP #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif
{-# LANGUAGE FlexibleInstances #-}
{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for Frontend.
--   Generated by the BNF converter.

module Frontend.Zedex.Print where

import qualified Frontend.Zedex.Abs
import Data.Char

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Frontend.Zedex.Abs.Id where
  prt _ (Frontend.Zedex.Abs.Id (_,i)) = doc $ showString $ i
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print Frontend.Zedex.Abs.Scalar where
  prt _ (Frontend.Zedex.Abs.Scalar i) = doc $ showString $ i

instance Print Frontend.Zedex.Abs.Program where
  prt i e = case e of
    Frontend.Zedex.Abs.Progr toplevels -> prPrec i 0 (concatD [prt 0 toplevels])

instance Print [Frontend.Zedex.Abs.Toplevel] where
  prt = prtList

instance Print Frontend.Zedex.Abs.Toplevel where
  prt i e = case e of
    Frontend.Zedex.Abs.ToplF id ids expr -> prPrec i 0 (concatD [prt 0 id, prt 0 ids, doc (showString ":="), prt 0 expr])
    Frontend.Zedex.Abs.ToplX complex ids expr -> prPrec i 0 (concatD [doc (showString "\958"), doc (showString "("), prt 0 complex, doc (showString ")"), prt 0 ids, doc (showString ":="), prt 0 expr])
    Frontend.Zedex.Abs.ToplZ complex ids expr -> prPrec i 0 (concatD [doc (showString "\950"), doc (showString "("), prt 0 complex, doc (showString ")"), prt 0 ids, doc (showString ":="), prt 0 expr])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print Frontend.Zedex.Abs.Expr where
  prt i e = case e of
    Frontend.Zedex.Abs.EVar id -> prPrec i 3 (concatD [prt 0 id])
    Frontend.Zedex.Abs.ETup expr exprs -> prPrec i 3 (concatD [doc (showString "("), prt 0 expr, doc (showString ","), prt 0 exprs, doc (showString ")")])
    Frontend.Zedex.Abs.EUnit -> prPrec i 3 (concatD [doc (showString "("), doc (showString ")")])
    Frontend.Zedex.Abs.EApp expr1 expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 3 expr2])
    Frontend.Zedex.Abs.EComp expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "\8728"), prt 1 expr2])
    Frontend.Zedex.Abs.EHad expr -> prPrec i 1 (concatD [doc (showString "~"), prt 1 expr])
    Frontend.Zedex.Abs.EAbs ids expr -> prPrec i 1 (concatD [doc (showString "\955"), prt 0 ids, doc (showString "."), prt 0 expr])
    Frontend.Zedex.Abs.EXAbs complex ids expr -> prPrec i 1 (concatD [doc (showString "\958"), doc (showString "("), prt 0 complex, doc (showString ")"), prt 0 ids, doc (showString "."), prt 0 expr])
    Frontend.Zedex.Abs.EZAbs complex ids expr -> prPrec i 1 (concatD [doc (showString "\950"), doc (showString "("), prt 0 complex, doc (showString ")"), prt 0 ids, doc (showString "."), prt 0 expr])
  prtList _ [x] = concatD [prt 0 x]
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [Frontend.Zedex.Abs.Expr] where
  prt = prtList

instance Print [Frontend.Zedex.Abs.Id] where
  prt = prtList

instance Print Frontend.Zedex.Abs.Complex where
  prt i e = case e of
    Frontend.Zedex.Abs.CComp scalar1 scalar2 -> prPrec i 2 (concatD [prt 0 scalar1, doc (showString "+"), prt 0 scalar2, doc (showString "i")])
    Frontend.Zedex.Abs.CComn scalar1 scalar2 -> prPrec i 2 (concatD [prt 0 scalar1, doc (showString "-"), prt 0 scalar2, doc (showString "i")])
    Frontend.Zedex.Abs.CPi -> prPrec i 2 (concatD [doc (showString "\960")])
    Frontend.Zedex.Abs.CE -> prPrec i 2 (concatD [doc (showString "e")])
    Frontend.Zedex.Abs.CExp complex1 complex2 -> prPrec i 1 (concatD [prt 2 complex1, doc (showString "^"), prt 1 complex2])
    Frontend.Zedex.Abs.CDiv complex1 complex2 -> prPrec i 1 (concatD [prt 2 complex1, doc (showString "/"), prt 1 complex2])
    Frontend.Zedex.Abs.CMul complex1 complex2 -> prPrec i 1 (concatD [prt 2 complex1, prt 1 complex2])

